// SBTI questions data - used by script.js
var __sbti_questions = [
  { id: 1, text: "群聊里突然有人发了个大红包，你的第一反应？", options: [
    { text: "光速抢，抢到0.01也开心", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "等别人先抢，看看气氛再说", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "抢完发个表情包活跃气氛", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "假装没看到，反正抢不到大的", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 2, text: "朋友约你周末出去玩，你内心OS是？", options: [
    { text: "走走走！去哪都行！", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "让我看看那天有没有别的安排……其实就是想在家躺", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "行，但是几点？在哪？吃什么？先说清楚", scores: { A: 0, S: 1, D: 1, W: 1 } },
    { text: "先答应再说，到时候看心情决定去不去", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 3, text: "聚会时你迟到了，进门第一句话是？", options: [
    { text: "不好意思不好意思！堵车了！", scores: { A: 1, S: 1, D: 0, W: 1 } },
    { text: "悄悄坐到角落，假装自己一直在", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "来了来了！谁点菜了？没点我加几个", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "淡定走进来，迟到是我的风格", scores: { A: 0, S: 0, D: 1, W: 0 } },
  ]},
  { id: 4, text: "朋友圈有人发了自拍，你的操作是？", options: [
    { text: "秒赞，顺便评论夸好看", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "默默看完，划走，什么都不做", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "截图发给闺蜜/兄弟一起讨论", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "点个赞，心里想'下次我也发一张'", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 5, text: "聚餐时大家开始AA算账，你的状态？", options: [
    { text: "主动打开计算器，精确到分", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "别人说多少就多少，懒得算", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "默默算了一下发现自己亏了但不说", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "提议下次换个人请客，这次先AA", scores: { A: 0, S: 1, D: 1, W: 0 } },
  ]},
  { id: 6, text: "被拉进一个完全不认识的群，你会？", options: [
    { text: "立刻发个'大家好'刷存在感", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "潜水观察三天再决定要不要说话", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "直接退群，多一个群多一份打扰", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "改个低调的群昵称，假装老成员", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 7, text: "朋友失恋了找你倾诉，你的反应？", options: [
    { text: "陪TA骂前任骂三个小时不带停", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "认真分析问题出在哪里", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "说'别难过了，请你吃顿好的'", scores: { A: 1, S: 1, D: 0, W: 1 } },
    { text: "发一堆搞笑表情包试图逗笑TA", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 8, text: "在电梯里遇到不太熟的同事，你会？", options: [
    { text: "主动打招呼聊天气", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "假装看手机，避免眼神接触", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "微笑点头，然后沉默到出电梯", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "疯狂按关门键希望没人进来", scores: { A: 1, S: 0, D: 1, W: 0 } },
  ]},
  { id: 9, text: "有人给你发了一条语音消息，60秒，你的反应？", options: [
    { text: "直接点开听，耐心听完", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "看到60秒就头皮发麻，转文字", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "先收藏，告诉自己'等会儿听'然后永远没听", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "回一句'打字行吗'，然后内心觉得自己好冷漠", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 10, text: "朋友借了你200块钱，三个月没还，你会？", options: [
    { text: "直接开口要，200块也是钱", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "暗示几次，比如'最近好穷啊'", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "算了，就当请客了，但心里记着", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "下次TA请吃饭的时候多点几个菜", scores: { A: 0, S: 1, D: 1, W: 0 } },
  ]},
  { id: 11, text: "在KTV里别人递给你话筒，你的反应？", options: [
    { text: "接过话筒直接开唱，管它跑不跑调", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "摆手说'我不唱不唱'然后默默跟着哼", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "点一首最拿手的，展示真正的实力", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "接过话筒但只唱副歌部分", scores: { A: 0, S: 1, D: 0, W: 1 } },
  ]},
  { id: 12, text: "过年被亲戚问'有对象了吗'，你怎么回？", options: [
    { text: "微笑说'还在找呢'，内心翻白眼", scores: { A: 0, S: 1, D: 0, W: 1 } },
    { text: "直接说'没有，不着急'，结束话题", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "反问对方'您家孩子期末考多少分'", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "说'有了有了'然后编一个离谱的故事", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 13, text: "朋友在群里发了张丑照，你被拍得特别丑，你？", options: [
    { text: "要求对方立刻删除，不然绝交", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "自黑一波'这角度绝了'", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "保存下来，等TA发丑照的时候反击", scores: { A: 0, S: 0, D: 1, W: 0 } },
    { text: "假装没看到，默默把群消息设为免打扰", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 14, text: "你发了一条朋友圈，一小时没人点赞，你？", options: [
    { text: "删了删了，假装什么都没发生过", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "无所谓，发朋友圈又不是为了点赞", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "去给别人点赞，期待回赞", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "分析一下是不是发的时间不对", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 15, text: "新来的同事主动加你微信，你？", options: [
    { text: "热情通过，发个欢迎表情包", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "通过但不主动说话，等对方先开口", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "通过后简单聊两句，建立基本联系", scores: { A: 0, S: 1, D: 1, W: 1 } },
    { text: "犹豫半天要不要通过，最后通过了", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 16, text: "约饭时选餐厅，你的风格是？", options: [
    { text: "我来选！我知道一家超好吃的！", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "你们选吧，我什么都行", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "打开大众点评，对比评分、距离、价格", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "提一个，被否了就'那随便吧'", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 17, text: "在群里不小心发了不该发的内容，你？", options: [
    { text: "光速撤回，假装无事发生", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "发个'发错了'然后继续聊", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "如果有人看到了就自黑化解尴尬", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "退出群聊，换个号重新做人", scores: { A: 1, S: 0, D: 1, W: 0 } },
  ]},
  { id: 18, text: "朋友给你安利一部番/剧，你的反应？", options: [
    { text: "马上去看！信你的品味！", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "先记下来，加入'以后看'清单（永远不会看）", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "先去豆瓣查评分，8分以上再看", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "嘴上说好好好，心里想'又来了'", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 19, text: "有人在你面前哭了，你怎么办？", options: [
    { text: "递纸巾，然后默默陪着不说话", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "手足无措，想安慰但不知道说什么", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "拍拍肩膀说'没事的，都会好的'", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "分析TA为什么哭，试图从根源解决问题", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 20, text: "你发现自己被拉黑了，第一反应？", options: [
    { text: "疯狂回忆自己说了什么", scores: { A: 1, S: 0, D: 0, W: 0 } },
    { text: "无所谓，拉黑就拉黑呗", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "找共同好友打听发生了什么", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "也把对方拉黑，礼尚往来", scores: { A: 1, S: 0, D: 1, W: 0 } },
  ]},
  { id: 21, text: "朋友突然说'我有事跟你说'，你？", options: [
    { text: "紧张！是不是出什么事了？快说！", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "淡定回复'怎么了'，内心已经脑补了一百种可能", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "直接打电话过去，打字说不清楚", scores: { A: 1, S: 1, D: 1, W: 1 } },
    { text: "等对方说，不主动追问", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 22, text: "参加一个全是陌生人的聚会，你会？", options: [
    { text: "主动找话题，迅速融入", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "找角落坐着，疯狂刷手机", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "先观察一圈，找一个看起来最友善的人搭话", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "等认识的人来了一起行动", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 23, text: "有人给你发了一条'在吗'，你？", options: [
    { text: "秒回'在'，然后等下文", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "看到'在吗'就不想回了", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "过半小时再回'刚看到，怎么了'", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "回一个问号，让对方自己说", scores: { A: 0, S: 0, D: 1, W: 0 } },
  ]},
  { id: 24, text: "你生日那天，最希望收到什么？", options: [
    { text: "一大群朋友给我办个surprise派对", scores: { A: 1, S: 1, D: 0, W: 0 } },
    { text: "一个人安安静静过就好", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "收到一个我真正想要很久的东西", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "不在乎形式，有人记得就行", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 25, text: "朋友之间吵架了，你会怎么做？", options: [
    { text: "主动去找对方谈，把话说开", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "等对方先来找自己，毕竟不是我的错", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "冷战三天，然后假装什么都没发生", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "发一段长消息把想法全说出来", scores: { A: 0, S: 0, D: 1, W: 0 } },
  ]},
  { id: 26, text: "路上遇到一个很久没见的熟人，你？", options: [
    { text: "热情打招呼，聊个五毛钱的", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "低头假装看手机快速走过", scores: { A: 0, S: 0, D: 1, W: 0 } },
    { text: "犹豫要不要打招呼，犹豫完人已经走远了", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "微笑点头致意，不停下脚步", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 27, text: "朋友问你'我胖了吗'，你怎么回答？", options: [
    { text: "没有没有！你看起来很好！", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "确实有点，不过不影响", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "转移话题'我们去吃点什么吧'", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "'你在我心里永远是瘦的'（土味情话）", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 28, text: "你被邀请当伴郎/伴娘，你的反应？", options: [
    { text: "太荣幸了！我一定到场！", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "开心但开始焦虑要花多少钱随份子", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "先问清楚要做什么，评估一下工作量", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "答应下来但内心社恐发作", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 29, text: "你发现朋友在背后说你坏话，你？", options: [
    { text: "直接当面质问", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "默默疏远，不再来往", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "找机会在朋友圈内涵一下", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "反思一下是不是自己真的有问题", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 30, text: "有人不停给你发消息，你不想回，你会？", options: [
    { text: "直接说'在忙，晚点聊'", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "已读不回，等TA自己识趣", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "隔很久回一个'嗯''哦'敷衍", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "设置消息免打扰，假装没看到", scores: { A: 0, S: 0, D: 1, W: 0 } },
  ]},
  { id: 31, text: "你发消息给朋友，TA一直不回，你？", options: [
    { text: "继续发，可能TA没看到", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "等，等到TA回为止", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "想多了，可能在忙，不纠结", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "截图给另一个朋友吐槽'又不回消息'", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 32, text: "朋友要搬家找你帮忙，你？", options: [
    { text: "二话不说就去了，还自带零食", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "答应去但内心在计算这得累死", scores: { A: 0, S: 1, D: 0, W: 1 } },
    { text: "说那天有事去不了，但可以帮找搬家公司", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "去是去，但全程摸鱼只干轻活", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 33, text: "聚会时玩真心话大冒险，你选？", options: [
    { text: "真心话！我没什么不能说的", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "大冒险！做就做，谁怕谁", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "尽量不玩，找借口去洗手间", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "选真心话但回答超敷衍", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 34, text: "有人送了你一个很丑的礼物，你？", options: [
    { text: "笑着说谢谢，回头塞柜子最深处", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "真诚地说'哇好特别啊谢谢'", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "当场就问'这哪买的'", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "收下但内心想'这审美绝了'", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 35, text: "你发现你的好朋友和你讨厌的人玩得很好，你？", options: [
    { text: "无所谓，朋友的朋友不关我事", scores: { A: 0, S: 1, D: 0, W: 1 } },
    { text: "心里有点不舒服但不说", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "跟朋友表达一下自己的感受", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "重新审视这段友谊", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 36, text: "你发了一条动态，有人评论杠你，你？", options: [
    { text: "直接怼回去", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "无视，不跟这种人一般见识", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "删掉评论，保持页面干净", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "截图发给朋友一起吐槽", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 37, text: "你和朋友同时看上了同一个东西（最后一件），你？", options: [
    { text: "让给朋友，毕竟友谊第一", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "谁先拿到算谁的", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "提议猜拳决定", scores: { A: 0, S: 1, D: 1, W: 0 } },
    { text: "说'算了我不那么想要'（其实超想要）", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 38, text: "朋友突然说想创业找你入伙，你？", options: [
    { text: "好啊！一起干！年轻人就是要拼！", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "先看看商业计划书再说", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "委婉拒绝，打工挺好的", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "说'我考虑考虑'然后无限期拖延", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 39, text: "你被放鸽子了，对方临时说有事来不了，你？", options: [
    { text: "没事没事，下次再约", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "有点生气但不说，自己一个人去", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "说'行吧'然后立刻约别人", scores: { A: 1, S: 1, D: 1, W: 1 } },
    { text: "松了一口气，正好可以宅家", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 40, text: "你在一个500人的大群里，你会？", options: [
    { text: "偶尔冒泡，刷一下存在感", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "永远潜水，除非@我", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "当群里的气氛担当，经常发段子", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "设为免打扰，偶尔翻翻有没有重要消息", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 41, text: "周一早上闹钟响了，你的反应？", options: [
    { text: "一骨碌爬起来，新的一周冲冲冲", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "关掉闹钟，再睡5分钟……然后迟到了", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "躺床上刷手机15分钟再起", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "内心呐喊'为什么周末这么短'然后不情不愿地起", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 42, text: "开会的时候你通常在干嘛？", options: [
    { text: "认真做笔记，积极发言", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "表面认真，实际在桌子底下刷手机", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "偷偷给同事发消息吐槽", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "思考会议内容，等结束提建设性意见", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 43, text: "老板让你加班，你内心OS？", options: [
    { text: "行吧，加班费/调休到位就行", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "表面答应，内心已经提了离职（并没有）", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "直接问有没有加班费", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "赶紧干完赶紧走，效率拉满", scores: { A: 1, S: 0, D: 1, W: 1 } },
  ]},
  { id: 44, text: "摸鱼被抓到了，你怎么应对？", options: [
    { text: "淡定切回工作界面，假装一直在工作", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "尴尬一笑'刚回了个消息'", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "理直气壮'我在查资料'", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "内心慌得一批，表面稳如老狗", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 45, text: "考试前一天晚上，你在干嘛？", options: [
    { text: "疯狂复习，临时抱佛脚", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "该吃吃该睡睡，已经复习过了", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "焦虑到睡不着，但也没在复习", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "打游戏放松，明天看命", scores: { A: 1, S: 0, D: 0, W: 0 } },
  ]},
  { id: 46, text: "写报告/论文时你的状态是？", options: [
    { text: "列好大纲，按部就班写", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "DDL前一晚开始疯狂输出", scores: { A: 1, S: 0, D: 0, W: 0 } },
    { text: "写一段删一段，反复修改", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "先写完初稿，再慢慢改", scores: { A: 1, S: 0, D: 1, W: 1 } },
  ]},
  { id: 47, text: "同事把功劳抢了，你怎么办？", options: [
    { text: "当场指出'这个是我做的'", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "算了，下次注意留证据", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "私下跟老板说明情况", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "跟朋友吐槽但不实际处理", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 48, text: "你理想的工作状态是？", options: [
    { text: "每天忙碌充实，有成就感", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "钱多事少离家近", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "和喜欢的人一起工作，氛围好", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "有自由度，能自己安排时间", scores: { A: 0, S: 0, D: 1, W: 0 } },
  ]},
  { id: 49, text: "上班/上学路上遇到堵车，你？", options: [
    { text: "焦虑地看时间，不停刷新导航", scores: { A: 1, S: 0, D: 0, W: 1 } },
    { text: "淡定听歌，反正急也没用", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "给同事/同学发消息说可能迟到", scores: { A: 0, S: 1, D: 1, W: 1 } },
    { text: "开始规划如果迟到了怎么解释", scores: { A: 0, S: 0, D: 1, W: 0 } },
  ]},
  { id: 50, text: "你犯了一个工作/学习上的错误，你？", options: [
    { text: "立刻承认并想办法补救", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "先看看有没有人发现", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "自己默默改掉，不告诉任何人", scores: { A: 0, S: 0, D: 1, W: 0 } },
    { text: "焦虑一整天，觉得天要塌了", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 51, text: "领导/老师表扬了你，你的反应？", options: [
    { text: "开心但表面淡定'谢谢'", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "内心狂喜，回家发朋友圈（仅自己可见）", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "觉得是应该的，继续保持", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "跟朋友炫耀一下", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 52, text: "下午三点，你的工作效率？", options: [
    { text: "依然精神饱满，继续冲", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "开始犯困，需要咖啡续命", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "已经进入下班倒计时模式", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "去茶水间摸鱼聊天", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 53, text: "你被分配了一个完全不会的任务，你？", options: [
    { text: "硬着头皮上，边做边学", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "先问清楚要求，再决定怎么做", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "找会的人帮忙/请教", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "先拖一拖，说不定会取消", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 54, text: "你更喜欢哪种工作/学习方式？", options: [
    { text: "团队协作，大家一起头脑风暴", scores: { A: 1, S: 1, D: 0, W: 0 } },
    { text: "独立完成，不被打扰", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "先自己想，再跟人讨论", scores: { A: 0, S: 0, D: 1, W: 0 } },
    { text: "看心情，有时候合作有时候独立", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 55, text: "下班/放学后，你最想做什么？", options: [
    { text: "回家躺平，什么都不想干", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "约朋友出去吃饭聊天", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "继续做自己的事情（副业/爱好）", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "刷手机到凌晨两点", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 56, text: "你的桌面/书桌状态通常是？", options: [
    { text: "整整齐齐，东西各有各的位置", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "看起来乱但我知道东西在哪", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "已经乱到找不到东西了", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "定期大扫除，但很快又乱了", scores: { A: 1, S: 0, D: 0, W: 0 } },
  ]},
  { id: 57, text: "面对一个deadline，你通常？", options: [
    { text: "提前完成，绝不拖延", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "最后一天才开始，效率奇高", scores: { A: 1, S: 0, D: 0, W: 0 } },
    { text: "分阶段完成，每天做一点", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "焦虑但不行动，直到最后一刻爆发", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 58, text: "你在团队里通常是扮演什么角色？", options: [
    { text: "领导者，分配任务把控方向", scores: { A: 1, S: 1, D: 1, W: 1 } },
    { text: "执行者，让我干嘛我干嘛", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "智囊团，负责出主意", scores: { A: 0, S: 0, D: 1, W: 0 } },
    { text: "气氛组，负责活跃气氛", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 59, text: "你收到一封写着'紧急'的邮件，你？", options: [
    { text: "立刻打开看", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "先看看发件人是谁再决定", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "等一会儿再看，可能没那么紧急", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "内心叹气，又来事了", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 60, text: "你更喜欢哪种类型的任务？", options: [
    { text: "有挑战性的，能学到新东西", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "简单的重复性工作，不用动脑", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "有创造性的，能发挥自己的想法", scores: { A: 1, S: 0, D: 0, W: 0 } },
    { text: "跟人打交道的，越热闹越好", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 61, text: "同事/同学请你帮忙，你其实很忙，你？", options: [
    { text: "先帮TA，自己的事晚点再做", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "委婉拒绝'我现在有点忙'", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "帮一半，然后说'剩下的你自己试试'", scores: { A: 0, S: 1, D: 0, W: 1 } },
    { text: "直接说'没空'", scores: { A: 1, S: 0, D: 1, W: 1 } },
  ]},
  { id: 62, text: "你的备忘录里通常记什么？", options: [
    { text: "工作/学习计划，井井有条", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "各种账号密码（还不加密）", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "灵感、段子、想发的朋友圈", scores: { A: 1, S: 0, D: 0, W: 0 } },
    { text: "备忘录是什么？我不用", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 63, text: "你午休时间通常怎么过？", options: [
    { text: "趴桌子睡觉，雷打不动", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "跟同事一起吃饭聊天", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "刷手机/看视频", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "继续工作/学习，卷就完事了", scores: { A: 1, S: 0, D: 1, W: 1 } },
  ]},
  { id: 64, text: "你对自己的职业/学业规划？", options: [
    { text: "有清晰的五年计划", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "走一步看一步，船到桥头自然直", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "有个大方向但具体没想好", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "每天都在想但从未行动", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 65, text: "你在群里被@回答问题，你不知道答案，你？", options: [
    { text: "直接说'我也不太清楚'", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "百度一下再回复", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "假装没看到", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "@另一个可能知道的人", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 66, text: "你跟领导/老师单独谈话时，你？", options: [
    { text: "紧张到手心出汗", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "正常交流，就当跟普通人聊天", scores: { A: 1, S: 1, D: 1, W: 1 } },
    { text: "提前想好要说什么，有备而来", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "疯狂点头，不管对方说什么", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 67, text: "你发现一个同事/同学在摸鱼，你？", options: [
    { text: "关我什么事，我也在摸鱼", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "默默羡慕，TA好自在", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "跟TA一起摸鱼", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "专注自己的事，不被影响", scores: { A: 1, S: 0, D: 1, W: 1 } },
  ]},
  { id: 68, text: "你更喜欢哪种沟通方式？", options: [
    { text: "当面聊，效率最高", scores: { A: 1, S: 1, D: 1, W: 1 } },
    { text: "打字，可以慢慢想怎么说", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "电话，快速解决问题", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "邮件/文档，留有记录", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 69, text: "你完成了一项重要任务后的感觉？", options: [
    { text: "超有成就感！想跟所有人分享", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "松了一口气，终于搞定了", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "开始想下一个任务", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "奖励自己休息一下", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 70, text: "你被安排了额外的工作/作业，你？", options: [
    { text: "行，加就加吧（内心崩溃）", scores: { A: 0, S: 1, D: 0, W: 1 } },
    { text: "直接说'我手上已经很多了'", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "默默接下来，然后加班搞定", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "评估一下能不能推给别人", scores: { A: 0, S: 0, D: 1, W: 0 } },
  ]},
  { id: 71, text: "你在图书馆/自习室学习，旁边有人大声说话，你？", options: [
    { text: "戴上耳机，默默忍受", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "礼貌地请对方小声一点", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "换个位置，惹不起躲得起", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "在心里骂了一百遍", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 72, text: "你看到同事被领导批评了，你？", options: [
    { text: "假装没看到，避免尴尬", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "事后安慰一下", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "反思自己有没有同样的问题", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "跟其他同事八卦", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 73, text: "你换了一份新工作/新学校，你的适应速度？", options: [
    { text: "三天就混熟了", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "一个月左右才能适应", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "一直在适应中，到现在还没适应", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "主动出击，快速建立社交圈", scores: { A: 1, S: 1, D: 1, W: 1 } },
  ]},
  { id: 74, text: "你的闹钟有几个？", options: [
    { text: "一个就够了，说起就起", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "三个，每隔5分钟一个", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "五个起步，最后一个是'再不起就迟到了'", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "不需要闹钟，生物钟叫醒我", scores: { A: 1, S: 0, D: 1, W: 0 } },
  ]},
  { id: 75, text: "你更害怕哪种工作/学习场景？", options: [
    { text: "当众演讲/汇报", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "一个人做没人帮的项目", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "被安排完全不感兴趣的任务", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "跟难搞的人合作", scores: { A: 0, S: 1, D: 0, W: 1 } },
  ]},
  { id: 76, text: "你的电脑桌面壁纸是？", options: [
    { text: "默认壁纸，懒得换", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "喜欢的动漫/游戏角色", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "风景/极简风格", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "自己的照片/宠物", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 77, text: "你在网课/线上会议中通常？", options: [
    { text: "认真听讲做笔记", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "开着摄像头但人不在电脑前", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "关摄像头摸鱼", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "在聊天框跟同学吐槽", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 78, text: "你写代码/做作业遇到bug，你？", options: [
    { text: "死磕到底，不解决不睡觉", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "先搜Stack Overflow/百度", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "问同学/同事有没有遇到过", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "关电脑明天再说", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 79, text: "你参加培训/讲座时的状态？", options: [
    { text: "认真听讲，做笔记", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "前半段认真，后半段走神", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "全程刷手机", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "拍照PPT回去再看（永远不会看）", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 80, text: "你的工位/座位上有什么必备品？", options: [
    { text: "水杯+笔记本+笔，标准配置", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "零食+眼罩+抱枕，生存装备", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "手办/玩偶，精神寄托", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "降噪耳机，世界与我无关", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 81, text: "外卖小哥超时了20分钟，你？", options: [
    { text: "理解，天气不好/路况不好", scores: { A: 0, S: 1, D: 0, W: 1 } },
    { text: "有点不爽但不会说什么", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "已经饿了三个世纪了，催一下", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "给差评（犹豫很久最后还是没给）", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 82, text: "网购收到快递的那一刻，你的心情？", options: [
    { text: "像过年一样开心！拆快递！", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "淡定拆开，放一边", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "拆完发现跟想象的不一样，有点失落", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "拍个开箱照发朋友圈", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 83, text: "晚上睡不着的时候你在想什么？", options: [
    { text: "回忆今天尴尬的事，脚趾抠地", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "规划明天要做的事", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "脑补各种离谱剧情", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "数羊……数到1000还没睡着", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 84, text: "你的房间多久打扫一次？", options: [
    { text: "每天整理，一尘不染", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "一周一次大扫除", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "看不下去的时候才打扫", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "我妈来的时候打扫", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 85, text: "你出门前的必做事项？", options: [
    { text: "检查手机、钥匙、钱包三件套", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "照镜子，确认颜值在线", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "磨蹭到最后时刻才出门", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "提前出门，宁可早到不能迟到", scores: { A: 1, S: 0, D: 1, W: 1 } },
  ]},
  { id: 86, text: "你的洗衣习惯是？", options: [
    { text: "衣服穿一次就洗", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "攒到没有干净衣服了再洗", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "闻一闻，不臭就不洗", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "按颜色分类，认真洗", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 87, text: "你家的绿植现在怎么样了？", options: [
    { text: "什么绿植？我不养", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "养得很好，每天浇水", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "已经死了三盆了，还在买新的", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "买回来的时候什么样现在还什么样（假花）", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 88, text: "下雨天你更想做什么？", options: [
    { text: "窝在家里看电影/追番", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "出去淋雨（不是）", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "约朋友去咖啡馆", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "睡觉，下雨天最适合睡觉", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 89, text: "你丢东西后的反应？", options: [
    { text: "翻箱倒柜找，不找到不罢休", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "算了，丢了就丢了，再买一个", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "回忆最后一次见它在哪里", scores: { A: 0, S: 0, D: 1, W: 0 } },
    { text: "怪别人/怪环境，反正不是我的错", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 90, text: "你的手机电量低于多少会焦虑？", options: [
    { text: "低于50%就开始慌", scores: { A: 1, S: 0, D: 0, W: 1 } },
    { text: "低于20%才找充电器", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "5%？还能再撑一会儿", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "随身带充电宝，从不焦虑", scores: { A: 1, S: 0, D: 1, W: 1 } },
  ]},
  { id: 91, text: "你洗澡通常要多久？", options: [
    { text: "5分钟速战速决", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "15-20分钟正常速度", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "半小时起步，洗澡是思考人生的时间", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "一小时，在里面唱歌", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 92, text: "你看到家里的蟑螂，你？", options: [
    { text: "尖叫着跑出去", scores: { A: 1, S: 0, D: 0, W: 0 } },
    { text: "淡定地拿拖鞋拍死", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "假装没看到，它不犯我我不犯它", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "拍照发朋友圈'我家来了新室友'", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 93, text: "你早起后的第一件事是？", options: [
    { text: "看手机", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "刷牙洗脸", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "喝一杯水", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "再躺5分钟", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 94, text: "你的衣柜状态是？", options: [
    { text: "按颜色/季节分类整理", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "打开会塌出来的那种", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "永远觉得没衣服穿", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "一堆衣服但只穿那几件", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 95, text: "你做饭的水平如何？", options: [
    { text: "大厨级别，朋友都夸", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "能煮泡面，偶尔煎个蛋", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "厨房杀手，开火就报警", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "跟着教程做，味道看运气", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 96, text: "你更倾向于哪种居住环境？", options: [
    { text: "市中心，方便热闹", scores: { A: 1, S: 1, D: 1, W: 1 } },
    { text: "郊区，安静清幽", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "无所谓，在哪都能适应", scores: { A: 0, S: 1, D: 0, W: 1 } },
    { text: "跟朋友合租，有人陪", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 97, text: "你的睡眠习惯是？", options: [
    { text: "11点前入睡，规律作息", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "凌晨2点睡，中午12点起", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "失眠选手，每天都在跟睡眠作斗争", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "困了就睡，不困就不睡", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 98, text: "你收到快递发现是错的，你？", options: [
    { text: "联系客服退换", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "算了，懒得退了", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "看看能不能用，能用就留着", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "先拍照留证再联系客服", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 99, text: "你出门忘带手机了，你会？", options: [
    { text: "回去拿，没有手机活不了", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "慌张但继续走，反正也没那么重要", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "用别人的手机登录自己的微信", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "享受没有手机的自由时光（假装）", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 100, text: "你的周末通常怎么过？", options: [
    { text: "约朋友出去玩", scores: { A: 0, S: 1, D: 1, W: 0 } },
    { text: "在家躺两天", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "做平时没时间做的事", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "刷剧/打游戏到天昏地暗", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 101, text: "你看到邻居在装修，你的反应？", options: [
    { text: "忍了，谁家不装修呢", scores: { A: 0, S: 1, D: 0, W: 1 } },
    { text: "戴上耳机，世界与我无关", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "去跟邻居说能不能小声点", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "在业主群里吐槽", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 102, text: "你养宠物的话会养什么？", options: [
    { text: "狗！热情忠诚！", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "猫！独立高冷！", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "鱼/仓鼠，好养活", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "不养，自己都养不好", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 103, text: "你家的遥控器/钥匙经常？", options: [
    { text: "放在固定位置，从不丢", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "永远在找遥控器", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "到处都是，沙发缝里、枕头下面", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "买了一个找物器专门找它们", scores: { A: 1, S: 0, D: 1, W: 1 } },
  ]},
  { id: 104, text: "你的购物车里通常有多少东西？", options: [
    { text: "0件，看上就买", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "50件以上，大部分永远不会买", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "10件左右，等打折再买", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "购物车是什么？我直接下单", scores: { A: 1, S: 0, D: 1, W: 1 } },
  ]},
  { id: 105, text: "你做噩梦梦到什么最可怕？", options: [
    { text: "考试迟到/交白卷", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "被追赶跑不动", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "手机丢了/碎了", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "上班/上学迟到", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 106, text: "你发现被多收了钱，你？", options: [
    { text: "回去找商家退钱", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "算了，几块钱的事", scores: { A: 0, S: 1, D: 0, W: 1 } },
    { text: "心里不爽但不会去说", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "给差评", scores: { A: 0, S: 0, D: 1, W: 0 } },
  ]},
  { id: 107, text: "你家的Wi-Fi突然断了，你的反应？", options: [
    { text: "重启路由器，三分钟解决", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "崩溃，没有网我活不了", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "打电话给运营商投诉", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "用流量凑合，等它自己恢复", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 108, text: "你坐电梯遇到邻居，你？", options: [
    { text: "点头微笑打招呼", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "假装看手机", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "主动聊天，聊聊天气物业", scores: { A: 1, S: 1, D: 1, W: 1 } },
    { text: "等下一趟电梯", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 109, text: "你发现自己忘关水/煤气了，你？", options: [
    { text: "飞奔回家关掉", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "打电话给邻居/房东帮忙", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "应该没事吧……（焦虑一整天）", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "远程控制智能家居关掉", scores: { A: 1, S: 0, D: 1, W: 1 } },
  ]},
  { id: 110, text: "你每天步数大概多少？", options: [
    { text: "10000步以上，走路达人", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "2000步，从床到厕所到冰箱", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "5000步左右，正常水平", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "摇手机凑步数", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 111, text: "你更喜欢哪种天气？", options: [
    { text: "晴天，阳光明媚", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "阴天，不冷不热", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "下雨天，有氛围感", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "下雪天，浪漫", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 112, text: "你修东西的能力如何？", options: [
    { text: "什么都能修，人形修理机", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "只会重启，重启解决99%的问题", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "找教程跟着修，看运气", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "坏了就买新的", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 113, text: "你换季整理衣服时发现一件三年没穿的衣服，你？", options: [
    { text: "扔了/捐了，断舍离", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "留着吧，万一哪天穿呢", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "试穿一下，发现穿不上了，伤心", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "挂二手平台卖掉", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 114, text: "你更怕冷还是更怕热？", options: [
    { text: "怕冷，冬天是我的敌人", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "怕热，夏天是我的噩梦", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "都不怕，我很强", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "都怕，我只想待在25度的房间里", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 115, text: "你的钥匙/门禁卡经常丢吗？", options: [
    { text: "从不丢，我有固定位置", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "一个月丢一次", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "用指纹锁/密码锁，不需要钥匙", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "配了五把备用钥匙", scores: { A: 0, S: 0, D: 1, W: 0 } },
  ]},
  { id: 116, text: "你起床后发现今天没事，你的反应？", options: [
    { text: "太爽了！继续睡！", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "起来把平时没做的事做了", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "约朋友出去玩", scores: { A: 0, S: 1, D: 1, W: 0 } },
    { text: "刷手机度过美好的一天", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 117, text: "你看到一条'转发这条锦鲤会有好运'，你？", options: [
    { text: "转发！万一呢！", scores: { A: 1, S: 1, D: 0, W: 0 } },
    { text: "无视，迷信", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "点赞但不转发", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "截图发给朋友'你看这个好搞笑'", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 118, text: "你处理垃圾的方式？", options: [
    { text: "认真分类，环保从我做起", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "一股脑全扔一个袋子", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "攒到实在不行了再扔", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "让室友/家人去扔", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 119, text: "你的记账习惯是？", options: [
    { text: "每笔都记，月底复盘", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "记了三天就放弃了", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "不记账，钱嘛花了就花了", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "只用记账APP但经常忘记", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 120, text: "你看到小区里有流浪猫，你？", options: [
    { text: "买猫粮喂它", scores: { A: 1, S: 1, D: 0, W: 0 } },
    { text: "蹲下来摸摸它", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "拍照发朋友圈", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "看看就走，怕被抓", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 121, text: "暗恋一个人，你会？", options: [
    { text: "直接表白，成败在此一举", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "默默喜欢，不让他/她知道", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "疯狂暗示，希望对方能察觉", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "先试探一下对方的态度", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 122, text: "跟对象吵架了，你的处理方式？", options: [
    { text: "冷静一下再谈，避免说气话", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "当场就要说清楚", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "先道歉，不想吵架", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "冷战，等对方先开口", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 123, text: "你被表白了但不喜欢对方，你？", options: [
    { text: "直接拒绝，不拖泥带水", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "委婉拒绝'你很好但我配不上你'", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "说'让我想想'然后慢慢疏远", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "慌张到不知道说什么", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 124, text: "你觉得最好的安慰方式是？", options: [
    { text: "陪在身边，什么都不用说", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "给建议，帮忙分析问题", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "带TA去吃好吃的/玩好玩的", scores: { A: 1, S: 1, D: 0, W: 0 } },
    { text: "发搞笑内容转移注意力", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 125, text: "你一个人在深夜会感到孤独吗？", options: [
    { text: "会，但已经习惯了", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "不会，一个人挺好的", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "会，所以晚上会找人聊天", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "会，但刷刷手机就忘了", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 126, text: "你看到别人秀恩爱，你的反应？", options: [
    { text: "祝福！真甜！", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "酸了酸了，我什么时候才能有", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "划走，不想看", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "无所谓，跟我有什么关系", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 127, text: "你跟朋友闹翻了，多久能和好？", options: [
    { text: "当天就和好，憋不住", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "几天后，双方冷静下来", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "需要对方先给台阶", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "看事情严重程度", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 128, text: "你更在意别人的看法吗？", options: [
    { text: "很在意，经常因为别人的话纠结", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "不太在意，做自己就好", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "嘴上说不在意其实心里在意", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "只在意我在意的人的看法", scores: { A: 0, S: 1, D: 1, W: 0 } },
  ]},
  { id: 129, text: "你被夸奖时的反应？", options: [
    { text: "开心但谦虚'没有没有'", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "坦然接受'谢谢'", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "内心狂喜表面淡定", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "觉得对方在客套", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 130, text: "你被批评时的反应？", options: [
    { text: "虚心接受，努力改进", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "表面接受内心不服", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "当场反驳", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "回去之后反复想这件事", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 131, text: "你觉得自己是个什么样的人？", options: [
    { text: "外向开朗，社交达人", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "内向安静，思考者", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "表面社牛内心社恐", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "随遇而安，佛系人生", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 132, text: "你心情不好的时候会怎么做？", options: [
    { text: "找朋友倾诉", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "一个人待着消化", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "吃好吃的/买东西治愈自己", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "运动/打游戏发泄", scores: { A: 1, S: 0, D: 1, W: 0 } },
  ]},
  { id: 133, text: "你跟陌生人聊天会紧张吗？", options: [
    { text: "不会，跟谁都能聊", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "会，不知道说什么", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "看情况，有时候行有时候不行", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "紧张但努力假装不紧张", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 134, text: "你觉得友情和爱情哪个更重要？", options: [
    { text: "友情！朋友是一辈子的", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "爱情！甜甜的恋爱谁不想要", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "都重要，不冲突", scores: { A: 0, S: 1, D: 1, W: 0 } },
    { text: "都不重要，搞钱最重要", scores: { A: 1, S: 0, D: 1, W: 1 } },
  ]},
  { id: 135, text: "你分手后通常会？", options: [
    { text: "大哭一场然后删掉所有联系方式", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "慢慢走出来，时间治愈一切", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "找朋友疯狂倾诉", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "马上开始新生活", scores: { A: 1, S: 0, D: 1, W: 1 } },
  ]},
  { id: 136, text: "你更相信一见钟情还是日久生情？", options: [
    { text: "一见钟情！心跳的感觉", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "日久生情，慢慢了解才靠谱", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "都行，看感觉", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "都不信，我只信自己", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 137, text: "你看到前任有了新欢，你？", options: [
    { text: "祝福，过得好就行", scores: { A: 0, S: 1, D: 0, W: 1 } },
    { text: "内心复杂但表面无所谓", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "关我什么事，划走", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "截图发给朋友吐槽", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 138, text: "你觉得自己容易吃醋吗？", options: [
    { text: "超容易！但会忍住", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "不容易，我很大度", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "会吃醋但不会表现出来", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "直接说出来，不藏着掖着", scores: { A: 1, S: 0, D: 1, W: 0 } },
  ]},
  { id: 139, text: "你理想中的约会是？", options: [
    { text: "去游乐园/逛街，热热闹闹", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "在家一起做饭看电影", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "去一家有格调的餐厅", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "去旅行，一起探索新地方", scores: { A: 1, S: 1, D: 0, W: 0 } },
  ]},
  { id: 140, text: "你收到匿名的礼物，你？", options: [
    { text: "好奇到爆炸！到处打听是谁", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "先收下，慢慢猜", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "有点害怕，不会是什么陷阱吧", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "发朋友圈'有人送我礼物！'", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 141, text: "你觉得自己在感情中是？", options: [
    { text: "主动型，喜欢就追", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "被动型，等别人来追", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "看情况，有时候主动有时候被动", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "不主动也不被动，随缘", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 142, text: "你更害怕被拒绝还是被忽视？", options: [
    { text: "被拒绝，太伤自尊了", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "被忽视，存在感为零太难受", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "都不怕，做自己就好", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "都怕，所以我什么都不做", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 143, text: "你安慰人的方式通常是？", options: [
    { text: "拥抱+陪伴", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "讲道理+给建议", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "讲自己的类似经历让TA不孤单", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "用幽默化解悲伤", scores: { A: 1, S: 0, D: 0, W: 0 } },
  ]},
  { id: 144, text: "你觉得自己有社交恐惧吗？", options: [
    { text: "有，严重社恐", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "没有，我是社交达人", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "看场合，有时候有有时候没有", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "有但假装没有", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 145, text: "你更在意精神上的满足还是物质上的满足？", options: [
    { text: "精神上的，开心最重要", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "物质上的，有钱才有安全感", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "都要！我全都要！", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "看阶段，现在更在意物质", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 146, text: "你看到别人哭，你会跟着哭吗？", options: [
    { text: "会，共情能力太强了", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "不会，但会心疼", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "对亲近的人哭我会", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "不会，我是铁石心肠（不是）", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 147, text: "你看到感人的电影/番剧会哭吗？", options: [
    { text: "必哭，每次都哭", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "不会，但会被触动", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "偷偷擦眼泪不让别人看到", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "跟朋友一起看的时候假装不哭", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 148, text: "你觉得自己最大的优点是？", options: [
    { text: "善良，为别人着想", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "果断，做事不拖泥带水", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "乐观，什么困难都能扛过去", scores: { A: 1, S: 0, D: 0, W: 0 } },
    { text: "理性，遇事冷静分析", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 149, text: "你觉得自己最大的缺点是？", options: [
    { text: "太在意别人的感受", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "拖延症晚期", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "太冲动，容易后悔", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "想太多，行动力不够", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 150, text: "你看到别人在公共场合大声吵架，你？", options: [
    { text: "围观，吃瓜", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "赶紧走开，不想惹事", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "想上去劝架但不敢", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "假装没看到，低头走", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 151, text: "你追番/追剧的习惯是？", options: [
    { text: "一口气刷完一整季", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "每周等更新，跟着节奏看", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "先看别人评价再决定看不看", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "同时追好几部，来回切换", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 152, text: "你打游戏时的风格是？", options: [
    { text: "冲冲冲！先打了再说", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "猥琐发育，别浪", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "研究攻略，科学上分", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "佛系玩家，输赢无所谓", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 153, text: "你刷短视频通常刷多久？", options: [
    { text: "说好刷10分钟，两小时后还在刷", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "控制得很好，刷一会儿就停", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "只在上厕所/通勤时刷", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "不刷短视频，浪费时间", scores: { A: 1, S: 0, D: 1, W: 1 } },
  ]},
  { id: 154, text: "你在网上发帖/评论的风格是？", options: [
    { text: "活跃发言，经常被顶到热评", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "只看不发，沉默的潜水员", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "偶尔评论，但会反复编辑", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "只发正能量/有用的内容", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 155, text: "你看到一条热搜，你通常会？", options: [
    { text: "点进去看详情", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "扫一眼标题就划走", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "看评论比看正文有意思", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "转发给朋友讨论", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 156, text: "你的游戏段位/水平如何？", options: [
    { text: "大神级别，带飞全场", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "中等水平，不坑不C", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "菜但爱玩，快乐就完事了", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "不玩游戏", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 157, text: "你更喜欢哪种类型的番/剧？", options: [
    { text: "热血战斗，燃就完事了", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "恋爱日常，甜甜的", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "悬疑推理，烧脑的", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "搞笑沙雕，开心最重要", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 158, text: "你看到有人说你的偶像坏话，你？", options: [
    { text: "理性反驳，摆事实讲道理", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "直接开骂", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "无视，跟黑子计较什么", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "截图发粉丝群一起声讨", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 159, text: "你的B站/YouTube首页推荐都是什么？", options: [
    { text: "游戏解说/实况", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "知识科普/学习类", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "搞笑视频/鬼畜", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "美食/旅行vlog", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 160, text: "你打排位赛输了，你？", options: [
    { text: "再来一把！输了不睡！", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "心态崩了，关游戏冷静一下", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "怪队友，都是他们的锅", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "无所谓，娱乐而已", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 161, text: "你看到一个好笑的梗图，你？", options: [
    { text: "保存下来，以后用", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "转发给朋友一起笑", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "笑完就划走", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "自己P一个类似的", scores: { A: 1, S: 0, D: 1, W: 0 } },
  ]},
  { id: 162, text: "你更倾向于用哪个社交平台？", options: [
    { text: "微信，日常沟通必备", scores: { A: 0, S: 1, D: 0, W: 1 } },
    { text: "微博/小红书，吃瓜冲浪", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "B站/YouTube，看视频", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "QQ，跟二次元朋友聊天", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 163, text: "你在游戏里更偏向什么角色？", options: [
    { text: "输出/C位，我要carry", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "辅助/治疗，默默奉献", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "坦克/肉盾，冲锋在前", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "不固定，看阵容", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 164, text: "你看到一条'震惊！'标题的新闻，你？", options: [
    { text: "点进去看看（明知是标题党）", scores: { A: 1, S: 0, D: 0, W: 0 } },
    { text: "直接划走，假的", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "先看评论区真假", scores: { A: 0, S: 0, D: 1, W: 0 } },
    { text: "转发到群里'你们看这个'", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 165, text: "你的手机里装了多少个APP？", options: [
    { text: "50个以内，精简主义", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "100个左右，该有的都有", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "200个以上，下了一堆从来不用的", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "手机内存不够了但不想删", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 166, text: "你更喜欢单机游戏还是网游？", options: [
    { text: "单机，沉浸式体验", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "网游，跟朋友一起玩才有意思", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "都玩，看心情", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "手游，方便随时随地玩", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 167, text: "你看到UP主/博主更新了，你？", options: [
    { text: "第一时间点开看", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "先点赞收藏，以后看", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "等有空了再看", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "只看几分钟就划走", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 168, text: "你在游戏里遇到坑队友，你？", options: [
    { text: "打字喷TA", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "忍住不说，打完举报", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "安慰TA'没关系慢慢来'", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "直接挂机/退游戏", scores: { A: 1, S: 0, D: 1, W: 0 } },
  ]},
  { id: 169, text: "你的搜索记录里最多的是什么？", options: [
    { text: "各种教程/攻略", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "美食/外卖", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "各种奇怪的问题", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "不好意思说", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 170, text: "你看到有人在网上求助，你？", options: [
    { text: "如果知道答案就回复", scores: { A: 0, S: 1, D: 1, W: 0 } },
    { text: "围观，看看别人怎么回答", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "觉得跟我没关系，划走", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "点赞让更多人看到", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 171, text: "你更喜欢看直播还是看录播？", options: [
    { text: "直播，有互动感", scores: { A: 1, S: 1, D: 0, W: 0 } },
    { text: "录播，可以跳过不想看的", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "都看，看内容", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "都不看，我刷短视频", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 172, text: "你在游戏里抽卡/开箱子的运气如何？", options: [
    { text: "欧皇附体，一发入魂", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "非酋本酋，保底专业户", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "一般般，看运气", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "不抽卡/开箱，不花钱", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 173, text: "你看到一条谣言，你？", options: [
    { text: "查证后再决定信不信", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "先转发再说，万一是真的呢", scores: { A: 1, S: 1, D: 0, W: 0 } },
    { text: "看评论区有没有人辟谣", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "不理会，网上的东西不能全信", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 174, text: "你的表情包收藏有多少个？", options: [
    { text: "100个以内，够用就行", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "500个以上，聊天全靠表情包", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "经常存新的，但用的就那几个", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "不用表情包，打字", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 175, text: "你更倾向于看文字还是看视频获取信息？", options: [
    { text: "文字，快速高效", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "视频，更直观", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "看内容，不挑形式", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "播客/音频，解放双眼", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 176, text: "你看到有人在群里吵架，你？", options: [
    { text: "劝架，大家冷静一下", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "吃瓜，搬好小板凳", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "退群/免打扰，太吵了", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "站队，帮我觉得对的那一方", scores: { A: 1, S: 0, D: 1, W: 0 } },
  ]},
  { id: 177, text: "你更喜欢哪种类型的游戏？", options: [
    { text: "MOBA/竞技类，刺激", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "RPG/剧情类，沉浸", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "休闲/益智类，放松", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "沙盒/开放世界，自由探索", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 178, text: "你发朋友圈/动态的频率是？", options: [
    { text: "每天发，记录生活", scores: { A: 1, S: 1, D: 0, W: 0 } },
    { text: "一周几次，有内容才发", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "一个月一次，或者更少", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "从来不发", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 179, text: "你在网上看到有人分享自己的经历，你？", options: [
    { text: "认真看完，有时候会感动", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "快速划过，太长了", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "看评论区的反应", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "分享给可能有共鸣的朋友", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 180, text: "你更喜欢哪种类型的直播？", options: [
    { text: "游戏直播，看大神操作", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "聊天直播，听主播说话", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "知识/技能直播，学东西", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "不看直播", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 181, text: "你的浏览器标签页通常打开多少个？", options: [
    { text: "5个以内，用完就关", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "20个左右，'以后再看'", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "50个以上，电脑都卡了", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "太多不好意思说", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 182, text: "你看到一条'限时免费'的推送，你？", options: [
    { text: "立刻下载/领取，免费的不要白不要", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "看看是不是真的需要", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "忽略，又是套路", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "转发给朋友'这个免费'", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 183, text: "你在社交媒体上关注了多少人？", options: [
    { text: "50个以内，只关注最感兴趣的", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "100-300个，精选关注", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "500个以上，关注比粉丝多", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "不关注别人，只发自己的", scores: { A: 1, S: 0, D: 1, W: 0 } },
  ]},
  { id: 184, text: "你看到有人在网上发求助帖，你？", options: [
    { text: "认真回复，尽力帮忙", scores: { A: 0, S: 1, D: 1, W: 0 } },
    { text: "看看有没有人回了再说", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "点赞让更多人看到", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "划走，不关我事", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 185, text: "你打游戏时队友挂机了，你？", options: [
    { text: "打字骂TA然后举报", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "默默4打5，尽力而为", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "也挂机，摆烂", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "发全体消息'举报XX挂机'", scores: { A: 0, S: 1, D: 1, W: 0 } },
  ]},
  { id: 186, text: "你看到一条超长的帖子，你？", options: [
    { text: "认真看完每一个字", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "只看加粗/标题部分", scores: { A: 0, S: 0, D: 1, W: 0 } },
    { text: "太长了不看（TL;DR）", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "收藏'以后看'（永远不会看）", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 187, text: "你的微信置顶消息有几个？", options: [
    { text: "0个，不置顶", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "1-3个，最重要的", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "5个以上，重要的人/群都置顶", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "置顶了但消息太多还是看不到", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 188, text: "你看到一条'转发这条锦鲤'，你？", options: [
    { text: "转发！万一呢！", scores: { A: 1, S: 1, D: 0, W: 0 } },
    { text: "无视", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "点赞但不转发", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "评论'已转，坐等好运'", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 189, text: "你在游戏里被队友坑了，你？", options: [
    { text: "心态爆炸，疯狂打字", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "深呼吸，淡定", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "安慰队友'没事下把赢回来'", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "默默退出，不想玩了", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 190, text: "你更喜欢哪种二次元角色？", options: [
    { text: "热血男主，永不放弃", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "高冷天才，实力碾压", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "温柔治愈系，暖到心里", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "搞笑担当，笑到头掉", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 191, text: "你看到有人在网上分享自己的创作，你？", options: [
    { text: "认真欣赏，给好评", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "快速划过", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "挑毛病，评论区指点江山", scores: { A: 0, S: 0, D: 1, W: 0 } },
    { text: "点赞收藏鼓励一下", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 192, text: "你看到一条'你绝对想不到的XXX'，你？", options: [
    { text: "点！我就想知道！", scores: { A: 1, S: 0, D: 0, W: 0 } },
    { text: "划走，又是标题党", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "看评论区剧透", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "转发到群里'你们猜是什么'", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 193, text: "你看到有人在网上卖惨，你？", options: [
    { text: "同情，可能会帮忙", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "先判断真假再说", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "无视，网上的事不能全信", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "觉得是营销号，划走", scores: { A: 0, S: 0, D: 1, W: 0 } },
  ]},
  { id: 194, text: "你更喜欢看哪种类型的视频？", options: [
    { text: "知识科普，学到了", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "搞笑段子，笑就完事了", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "游戏实况，看别人玩", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "生活vlog，看别人的日常", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 195, text: "你在游戏里打到关键团战，你？", options: [
    { text: "冲！先手开团！", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "等队友先上，我在后面输出", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "疯狂发信号'打打打'", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "手抖，怕失误", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 196, text: "你看到有人在网上被网暴，你？", options: [
    { text: "为TA说话，仗义执言", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "不参与，怕被波及", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "觉得网络暴力太可怕了", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "举报那些网暴的人", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 197, text: "你更喜欢哪种弹幕文化？", options: [
    { text: "全程开弹幕，看弹幕比看视频有意思", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "关弹幕，清净", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "只开到一半，挡字幕了就关", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "自己也发弹幕互动", scores: { A: 1, S: 1, D: 1, W: 0 } },
  ]},
  { id: 198, text: "你看到有人在网上炫耀，你？", options: [
    { text: "酸了，但不说", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "真心祝福，人家努力得来的", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "划走，不想看", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "截图发给朋友吐槽", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 199, text: "你看到一条'今天你快乐吗'的投票，你？", options: [
    { text: "投'快乐'，即使不快乐", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "投'不快乐'，诚实面对", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "不投票，无聊", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "看看别人的投票结果", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 200, text: "你看到有人在网上说'我太难了'，你？", options: [
    { text: "感同身受，我也是", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "评论'加油'", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "划走，谁不难呢", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "点赞表示同情", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 201, text: "你看到一件超喜欢的衣服但很贵，你？", options: [
    { text: "咬牙买！人生苦短！", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "等打折再买", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "找平替/同款", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "算了，太贵了不值得", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 202, text: "你的消费观是？", options: [
    { text: "该省省该花花，不亏待自己", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "能省则省，存钱最重要", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "活在当下，享受生活", scores: { A: 1, S: 0, D: 0, W: 0 } },
    { text: "冲动消费选手，买了就后悔", scores: { A: 1, S: 0, D: 0, W: 0 } },
  ]},
  { id: 203, text: "你逛超市/便利店的风格是？", options: [
    { text: "列好清单，直奔目标", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "逛一圈，看到什么想买就买", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "只买打折商品", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "每条货架都逛一遍", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 204, text: "你和朋友出去吃饭，结账时你？", options: [
    { text: "主动请客", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "提议AA", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "等对方先说", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "假装去洗手间", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 205, text: "你冲动消费后通常会？", options: [
    { text: "退货！冷静下来就不想要了", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "安慰自己'买都买了'", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "后悔三天然后忘了", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "发朋友圈晒一下（假装很值得）", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 206, text: "你每个月能存下多少钱？", options: [
    { text: "工资的50%以上，理财达人", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "能存一点，但不多", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "月光族，存不下", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "负资产，花呗/信用卡选手", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 207, text: "你看到一件商品'买一送一'，你？", options: [
    { text: "买！两个更划算", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "想想自己需不需要两个", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "不需要就不买，送也不要", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "拉着朋友一起买，一人一个", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 208, text: "你借给别人钱的规则是？", options: [
    { text: "救急不救穷", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "好朋友就借，不问原因", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "一般不借，谈钱伤感情", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "看金额，小钱无所谓", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 209, text: "你逛商场/网购时最容易买什么？", options: [
    { text: "衣服/鞋子", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "电子产品/数码", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "零食/日用品", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "手办/周边/盲盒", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 210, text: "你看到'限时折扣'会？", options: [
    { text: "立刻下单，怕错过", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "先加购物车，等冷静一下", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "不受影响，需要才买", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "转发给朋友'这个打折了'", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 211, text: "你更愿意把钱花在什么上？", options: [
    { text: "吃！美食不可辜负", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "体验！旅行/演唱会", scores: { A: 1, S: 1, D: 0, W: 0 } },
    { text: "存起来，安全感", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "爱好！游戏/手办/追番", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 212, text: "你买了一件东西发现降价了，你？", options: [
    { text: "申请保价/退差价", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "算了，早买早享受", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "气死！再也不在这家买了", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "安慰自己'就当捐了'", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 213, text: "你更倾向于租房还是买房？", options: [
    { text: "买房，有自己的家", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "租房，自由灵活", scores: { A: 1, S: 0, D: 0, W: 0 } },
    { text: "看经济能力", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "跟父母住，省钱", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 214, text: "你看到朋友买了一个很贵的东西，你？", options: [
    { text: "'哇好好看！链接发我'", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "替TA心疼钱", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "无所谓，人家爱买啥买啥", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "暗暗比较自己有没有", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 215, text: "你买盲盒/抽卡的策略是？", options: [
    { text: "直接买隐藏款/保底", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "佛系抽，抽到什么是什么", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "不买，浪费钱", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "只买喜欢的那个，不赌", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 216, text: "你每个月的开销最大的是？", options: [
    { text: "房租/房贷", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "吃/外卖", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "购物/网购", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "娱乐/游戏", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 217, text: "你看到'充100送20'的活动，你？", options: [
    { text: "充！白送的钱不要白不要", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "算一下是不是真的划算", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "不充，套路太深", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "看是不是常用的平台", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 218, text: "你买电子产品更看重什么？", options: [
    { text: "性能/配置", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "外观/颜值", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "性价比", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "品牌", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 219, text: "你更愿意为体验还是为物品花钱？", options: [
    { text: "体验！旅行/演唱会/美食", scores: { A: 1, S: 1, D: 0, W: 0 } },
    { text: "物品！买了就是我的", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "看情况", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "都不花，省钱", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 220, text: "你看到'免费试用'的活动，你？", options: [
    { text: "立刻报名！免费的！", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "看看有没有坑", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "不参加，天下没有免费的午餐", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "转发给朋友一起薅羊毛", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 221, text: "你买完东西通常会看评价吗？", options: [
    { text: "买之前看，买之后写", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "买之前看，买之后不写", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "都不看，看感觉买", scores: { A: 1, S: 0, D: 0, W: 0 } },
    { text: "只看差评", scores: { A: 0, S: 0, D: 1, W: 0 } },
  ]},
  { id: 222, text: "你更愿意花钱请人还是自己动手？", options: [
    { text: "花钱请人，时间就是金钱", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "自己动手，省钱", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "看事情难度", scores: { A: 0, S: 0, D: 1, W: 0 } },
    { text: "自己不会才请人", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 223, text: "你看到'会员专享'的内容，你？", options: [
    { text: "充会员！我要看！", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "找免费资源", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "不看就不看，不花钱", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "借朋友的会员", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 224, text: "你收到账单/信用卡提醒时的心情？", options: [
    { text: "心痛，又花了这么多", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "淡定，在预算内", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "假装没看到", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "开始计划下个月省钱", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 225, text: "你买二手物品能接受吗？", options: [
    { text: "完全可以，省钱又环保", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "看是什么东西", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "不太能接受，想要全新的", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "自己不买但可以卖", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 226, text: "你看到'清仓大甩卖'的招牌，你？", options: [
    { text: "进去看看有没有好东西", scores: { A: 1, S: 0, D: 0, W: 0 } },
    { text: "继续走，清仓的都是卖不出去的", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "拉着朋友一起逛", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "拍照发朋友圈'清仓了'", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 227, text: "你买礼物通常花多少钱？", options: [
    { text: "看关系，越亲近越贵", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "固定预算，不超支", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "心意最重要，不看重价格", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "买最贵的，有面子", scores: { A: 1, S: 0, D: 1, W: 0 } },
  ]},
  { id: 228, text: "你看到'新用户专享优惠'，你？", options: [
    { text: "换号注册薅羊毛", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "让家人/朋友帮忙下单", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "算了，太麻烦", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "直接用老用户身份买", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 229, text: "你的钱包/卡包里有什么？", options: [
    { text: "各种会员卡，堆成山", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "只有身份证和银行卡", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "钱包？我手机支付", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "有零钱但不知道什么时候放的", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 230, text: "你看到'拼团更便宜'，你？", options: [
    { text: "拉人拼团！", scores: { A: 0, S: 1, D: 1, W: 0 } },
    { text: "等别人发起的团加入", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "差不了几块钱，直接买", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "不拼，怕麻烦", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 231, text: "你买东西更看重品牌还是性价比？", options: [
    { text: "品牌！质量有保障", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "性价比！好用就行", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "看心情", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "只买需要的，不挑品牌", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 232, text: "你看到'仅剩最后X件'的提示，你？", options: [
    { text: "赶紧买！不买就没了！", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "知道是营销手段，不理", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "犹豫一下，还是买了", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "真的最后几件吗？我不信", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 233, text: "你更愿意花钱学技能还是买享受？", options: [
    { text: "学技能，投资自己", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "买享受，开心最重要", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "都要！我全都要！", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "都不花，省钱", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 234, text: "你看到'满减活动'，你？", options: [
    { text: "凑单！一定要凑到满减门槛", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "本来就要买的刚好凑上", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "为了凑单买了一堆不需要的", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "懒得算，直接买", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 235, text: "你的省钱方式是？", options: [
    { text: "记账+预算", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "不买不需要的东西（但经常失败）", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "用优惠券/比价", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "省钱？什么省钱？", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 236, text: "你看到'年卡/季卡'的选项，你？", options: [
    { text: "算一下日均价格，划算就买", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "月卡就好，怕用不完", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "直接年卡，长期用更便宜", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "不买卡，用免费功能", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 237, text: "你买完东西后悔了怎么办？", options: [
    { text: "退货", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "挂二手平台卖掉", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "算了，自用吧", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "送人", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 238, text: "你看到'打卡集章换礼品'，你？", options: [
    { text: "冲！每天打卡！", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "太麻烦了，不参加", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "打了两天就忘了", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "礼品不够吸引我", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 239, text: "你买衣服更看重什么？", options: [
    { text: "好看！颜值即正义", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "舒服！穿着最重要", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "品牌！有面子", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "便宜！性价比", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 240, text: "你看到'推荐好物'的帖子，你？", options: [
    { text: "种草了！马上下单", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "先加入购物车冷静一下", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "看看评论区有没有人踩雷", scores: { A: 0, S: 0, D: 1, W: 0 } },
    { text: "觉得是广告，划走", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 241, text: "你旅游时更喜欢跟团还是自由行？", options: [
    { text: "自由行！自己做攻略", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "跟团，省心", scores: { A: 0, S: 1, D: 0, W: 1 } },
    { text: "看去哪，国内自由行国外跟团", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "跟朋友一起，怎么都行", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 242, text: "你在旅途中迷路了，你？", options: [
    { text: "打开导航，跟着走", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "问路人", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "跟着感觉走，迷路也是一种风景", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "慌张，赶紧找到回去的路", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 243, text: "你旅游时拍照的风格是？", options: [
    { text: "疯狂拍照，手机内存不够了", scores: { A: 1, S: 1, D: 0, W: 0 } },
    { text: "拍几张有意义的就好", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "用眼睛看，不拍照", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "专门找人帮我拍好看的照片", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 244, text: "你坐长途车/飞机时通常？", options: [
    { text: "睡觉", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "看剧/听歌", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "跟邻座聊天", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "看窗外的风景发呆", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 245, text: "你的旅行行李打包风格是？", options: [
    { text: "列清单，精确到每件物品", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "随便塞，能装下就行", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "带太多，回来一半没用上", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "极简主义，一个背包走天下", scores: { A: 1, S: 0, D: 1, W: 0 } },
  ]},
  { id: 246, text: "你更想去哪里旅游？", options: [
    { text: "热门景点，打卡拍照", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "小众目的地，避开人群", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "自然风光，山川湖海", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "美食之旅，为了吃而旅行", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 247, text: "你在旅途中遇到不愉快的事，你？", options: [
    { text: "当场投诉/维权", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "忍了，不想破坏旅行心情", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "发朋友圈/小红书吐槽", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "跟同行的人吐槽一下就算了", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 248, text: "你旅行时更喜欢什么交通方式？", options: [
    { text: "飞机，快速到达", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "高铁/火车，看沿途风景", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "自驾，自由自在", scores: { A: 1, S: 0, D: 0, W: 0 } },
    { text: "大巴，便宜", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 249, text: "你在旅行中的作息是？", options: [
    { text: "早出晚归，充分利用每一天", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "睡到自然醒，慢慢逛", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "跟着旅伴的节奏", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "白天逛晚上宅酒店", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 250, text: "你旅行时更喜欢住什么？", options: [
    { text: "星级酒店，享受", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "民宿/青旅，有特色", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "便宜的就行，反正就睡一晚", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "看评分选，不踩雷", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 251, text: "你旅行回来后通常会？", options: [
    { text: "立刻修图发朋友圈", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "整理照片，写游记", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "倒时差/休息，太累了", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "开始计划下一次旅行", scores: { A: 1, S: 0, D: 1, W: 0 } },
  ]},
  { id: 252, text: "你在旅途中遇到下雨，你？", options: [
    { text: "改变计划，去室内景点", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "雨中漫步，别有风味", scores: { A: 1, S: 0, D: 0, W: 0 } },
    { text: "在酒店待着，等雨停", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "买把伞继续走", scores: { A: 1, S: 0, D: 1, W: 1 } },
  ]},
  { id: 253, text: "你旅行时会不会带纪念品回来？", options: [
    { text: "必买！冰箱贴/明信片/钥匙扣", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "给朋友带特产", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "不买，占地方", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "拍照就是最好的纪念", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 254, text: "你坐地铁/公交时通常？", options: [
    { text: "刷手机", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "听音乐/播客", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "看窗外发呆", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "观察车厢里的人（暗中观察）", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 255, text: "你在旅途中更喜欢和谁一起？", options: [
    { text: "好朋友，热闹", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "一个人，自由", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "对象/家人，温馨", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "跟团认识新朋友", scores: { A: 1, S: 1, D: 1, W: 0 } },
  ]},
  { id: 256, text: "你旅行前会做攻略吗？", options: [
    { text: "做详细攻略，精确到分钟", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "大概了解一下就行", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "不做攻略，走到哪算哪", scores: { A: 1, S: 0, D: 0, W: 0 } },
    { text: "抄别人的攻略", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 257, text: "你在旅途中遇到语言不通，你？", options: [
    { text: "用翻译APP", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "手语+微笑，万能沟通", scores: { A: 1, S: 1, D: 0, W: 0 } },
    { text: "找会说中文的人帮忙", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "提前学几句当地语言", scores: { A: 0, S: 0, D: 1, W: 0 } },
  ]},
  { id: 258, text: "你在旅途中更喜欢什么活动？", options: [
    { text: "逛景点/博物馆", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "吃当地美食", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "户外运动/探险", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "购物/逛街", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 259, text: "你旅行时最怕什么？", options: [
    { text: "丢东西/丢证件", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "跟旅伴吵架", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "遇到坑人的商家", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "天气不好", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 260, text: "你旅行时拍照更倾向于？", options: [
    { text: "风景照", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "自拍/他拍", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "美食照", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "不拍照，用心感受", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 261, text: "你打车时更喜欢？", options: [
    { text: "网约车，方便", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "出租车，靠谱", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "公交/地铁，便宜", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "走路/骑车，环保健康", scores: { A: 1, S: 0, D: 0, W: 0 } },
  ]},
  { id: 262, text: "你在旅途中遇到陌生人搭话，你？", options: [
    { text: "热情回应，说不定能交到新朋友", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "礼貌回应但不深聊", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "假装听不懂", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "警惕，怕被骗", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 263, text: "你旅行时的消费观是？", options: [
    { text: "该花就花，来都来了", scores: { A: 1, S: 0, D: 0, W: 0 } },
    { text: "精打细算，能省则省", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "体验第一，价格第二", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "提前做好预算", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 264, text: "你旅行回来最想做什么？", options: [
    { text: "回家！想我的床！", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "整理照片发朋友圈", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "跟朋友分享旅途趣事", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "开始计划下一次旅行", scores: { A: 1, S: 0, D: 1, W: 0 } },
  ]},
  { id: 265, text: "你在旅途中遇到突发状况（如航班取消），你？", options: [
    { text: "立刻想办法解决", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "慌张，不知道怎么办", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "联系客服/机场处理", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "算了，顺其自然", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 266, text: "你在旅途中更喜欢什么节奏？", options: [
    { text: "紧凑，打卡尽可能多的景点", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "慢节奏，一个地方待一天", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "跟着感觉走", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "看旅伴的节奏", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 267, text: "你在旅途中遇到喜欢的店，你会？", options: [
    { text: "进去逛逛，买点纪念品", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "拍照打卡", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "看一眼就走", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "进去坐坐，感受当地氛围", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 268, text: "你旅行时最不能接受什么？", options: [
    { text: "行程被打乱", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "旅伴不合拍", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "被宰/被坑", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "天气不好", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 269, text: "你在旅途中更喜欢什么时候出门？", options: [
    { text: "一大早，趁人少", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "睡到自然醒再出门", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "下午出门，避开中午的太阳", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "晚上出门，夜景最美", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 270, text: "你旅行时会不会写日记/发动态？", options: [
    { text: "每天发朋友圈/小红书记录", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "写旅行日记", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "拍vlog", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "不发不写，自己记住就好", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 271, text: "你点奶茶时的选择是？", options: [
    { text: "固定一款，从不换", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "每次都试新品", scores: { A: 1, S: 0, D: 0, W: 0 } },
    { text: "看心情随机选", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "三分糖去冰，养生", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 272, text: "你吃火锅时的风格是？", options: [
    { text: "点一大桌子，吃不完也要点", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "适量就好，不浪费", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "鸳鸯锅，照顾所有人", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "辣锅！无辣不欢！", scores: { A: 1, S: 0, D: 1, W: 0 } },
  ]},
  { id: 273, text: "你点外卖通常花多长时间选？", options: [
    { text: "5分钟内搞定", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "半小时，选到崩溃", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "打开外卖APP然后刷了半小时短视频", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "固定几家轮着点", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 274, text: "你更倾向于自己做饭还是外卖？", options: [
    { text: "自己做饭，健康省钱", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "外卖，方便快捷", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "看心情，有时候做有时候点", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "不会做饭，只能外卖", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 275, text: "你在餐厅吃到难吃的菜，你？", options: [
    { text: "叫服务员过来反映", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "算了，将就吃", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "拍照给差评", scores: { A: 0, S: 0, D: 1, W: 0 } },
    { text: "跟朋友吐槽这家店不行", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 276, text: "你吃自助餐的策略是？", options: [
    { text: "先吃贵的，回本！", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "吃自己喜欢的，不管贵不贵", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "少吃多尝，每样都来一点", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "扶墙进扶墙出", scores: { A: 1, S: 0, D: 0, W: 0 } },
  ]},
  { id: 277, text: "你更喜欢吃什么口味的食物？", options: [
    { text: "辣！无辣不欢！", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "甜！甜品是生命", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "咸鲜，经典口味", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "酸！开胃", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 278, text: "你和朋友吃饭时，你通常是？", options: [
    { text: "点菜担当，照顾所有人的口味", scores: { A: 0, S: 1, D: 1, W: 0 } },
    { text: "什么都行，你们点吧", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "有自己的要求，会提出来", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "负责吃，不负责点", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 279, text: "你深夜饿了会？", options: [
    { text: "点外卖！", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "忍着，睡觉就不饿了", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "翻冰箱找吃的", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "泡面！深夜的灵魂食物", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 280, text: "你更喜欢哪种类型的餐厅？", options: [
    { text: "网红店，拍照好看", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "苍蝇馆子，味道好", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "连锁品牌，品质稳定", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "有特色的私房菜", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 281, text: "你吃到一个新奇的美食，你？", options: [
    { text: "拍照发朋友圈/小红书", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "默默吃完，记住味道", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "推荐给朋友'这个超好吃'", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "研究它的做法，回家试试", scores: { A: 1, S: 0, D: 1, W: 1 } },
  ]},
  { id: 282, text: "你点外卖最怕什么？", options: [
    { text: "送错了/漏了", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "等太久", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "味道跟图片差太多", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "配送费太贵", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 283, text: "你更喜欢什么饮品？", options: [
    { text: "奶茶/果茶", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "咖啡，续命必备", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "白开水/茶，养生", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "快乐水（可乐）", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 284, text: "你和朋友聚餐时，你？", options: [
    { text: "抢着买单", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "提议AA", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "等别人买单", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "这次你请下次我请", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 285, text: "你做饭时如果失败了，你？", options: [
    { text: "点外卖补救", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "硬着头皮吃完", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "倒掉重来", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "拍照发朋友圈'翻车了'", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 286, text: "你更喜欢吃中餐还是西餐？", options: [
    { text: "中餐！中国胃", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "西餐！有情调", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "日料/韩料也不错", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "什么都行，好吃就行", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 287, text: "你在食堂/快餐店的点餐速度？", options: [
    { text: "秒点，早就想好了", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "犹豫半天，后面的人都不耐烦了", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "看别人点什么跟着点", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "每次都点一样的", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 288, text: "你看到一家新开的餐厅，你？", options: [
    { text: "立刻去试试！", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "等别人评价再说", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "看看有没有优惠活动", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "不感兴趣，老店就够了", scores: { A: 0, S: 0, D: 0, W: 1 } },
  ]},
  { id: 289, text: "你吃早餐的习惯是？", options: [
    { text: "每天都吃，营养均衡", scores: { A: 1, S: 0, D: 1, W: 1 } },
    { text: "经常不吃，来不及", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "一杯咖啡/牛奶搞定", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "周末才好好吃", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 290, text: "你更喜欢什么烹饪方式？", options: [
    { text: "烧烤！人间烟火", scores: { A: 1, S: 1, D: 0, W: 0 } },
    { text: "火锅！万物皆可涮", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "清蒸/水煮，健康", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "油炸！虽然不健康但好吃", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 291, text: "你在超市看到试吃活动，你？", options: [
    { text: "试吃！免费的干嘛不吃", scores: { A: 1, S: 0, D: 0, W: 0 } },
    { text: "不好意思，假装没看到", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "试吃好吃就买", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "拉着朋友一起去试吃", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 292, text: "你更喜欢吃米饭还是面食？", options: [
    { text: "米饭！一顿不吃想得慌", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "面食！面条/馒头/饺子", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "都行，不挑", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "不吃主食，减肥", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 293, text: "你吃不完的食物会？", options: [
    { text: "打包带走", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "剩着，下次热一热吃", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "直接扔掉", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "硬撑吃完", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 294, text: "你更喜欢甜食还是咸食？", options: [
    { text: "甜食！蛋糕奶茶巧克力", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "咸食！咸的才有味道", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "看心情", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "咸甜之争？我都爱", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
  { id: 295, text: "你在咖啡店通常点什么？", options: [
    { text: "美式，简单纯粹", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "拿铁/卡布奇诺", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "各种花式特调", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "我不喝咖啡", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 296, text: "你看到美食博主推荐一家店，你？", options: [
    { text: "马上去打卡", scores: { A: 1, S: 0, D: 1, W: 0 } },
    { text: "先看看评论区真实评价", scores: { A: 0, S: 0, D: 1, W: 1 } },
    { text: "加入'想吃'清单（永远不会去）", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "觉得是广告，不信", scores: { A: 0, S: 0, D: 1, W: 1 } },
  ]},
  { id: 297, text: "你吃火锅时必点什么？", options: [
    { text: "肥牛/羊肉", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "毛肚/鸭肠", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "豆腐/蔬菜", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "全部都要！", scores: { A: 1, S: 1, D: 1, W: 0 } },
  ]},
  { id: 298, text: "你更喜欢堂食还是打包？", options: [
    { text: "堂食，氛围好", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "打包/外卖，省事", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "看心情", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "在家吃最舒服", scores: { A: 0, S: 0, D: 0, W: 0 } },
  ]},
  { id: 299, text: "你对食物的接受程度？", options: [
    { text: "什么都吃，来者不拒", scores: { A: 1, S: 1, D: 1, W: 0 } },
    { text: "有点挑食，不吃XX", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "只吃熟悉的食物", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "愿意尝试新东西", scores: { A: 1, S: 0, D: 0, W: 0 } },
  ]},
  { id: 300, text: "如果只能选一种食物吃一辈子，你选？", options: [
    { text: "火锅！什么都能涮", scores: { A: 0, S: 1, D: 0, W: 0 } },
    { text: "米饭+菜，简单幸福", scores: { A: 0, S: 0, D: 0, W: 1 } },
    { text: "泡面！方便又好吃", scores: { A: 0, S: 0, D: 0, W: 0 } },
    { text: "奶茶！续命水", scores: { A: 0, S: 1, D: 0, W: 0 } },
  ]},
];
